### ISSUE TITLE
LAN API or Cloud API

### ISSUE THREAD

**Issue by ceboxsell** [kz/lifx-jasper#1]
Hi, in your read me you say you are using the cloud API to do this but you are installing LIFX-SDK which is a LAN SDK and you are using this API to communicate with devices not the HTTP API.

This would mean you don't need a token as everything is local to your network.

**Comment by kz** [comment]
I'm aware of this. The reason why there's a discrepancy is because this is in active development. By active, I mean I'm literally working on this now and have been working on it for the past couple hours. 

I'm currently implementing a way for this to interface with both LAN and cloud.
